# Predict house pricing using advanced regression

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df1=pd.read_csv("hptrain.csv")
df2=pd.read_csv("hptest.csv")

In [3]:
df=df1.append(df2)

/var/folders/rh/09l5x5h52b18cydcdhf8gr240000gn/T/ipykernel_61235/2456558213.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df1.append(df2)

Data fields
Here&#39;s a brief version of what you&#39;ll find in the data description file.
1. SalePriceÂ - the property&#39;s sale price in dollars. This is the target variable that you&#39;re
trying to predict.
2. MSSubClass: The building class
3. MSZoning: The general zoning classification
4. LotFrontage: Linear feet of street connected to property
5. LotArea: Lot size in square feet
6. Street: Type of road access
7. Alley: Type of alley access
8. LotShape: General shape of property
9. LandContour: Flatness of the property
10. Utilities: Type of utilities available
11. LotConfig: Lot configuration
12. LandSlope: Slope of property
13. Neighborhood: Physical locations within Ames city limits
14. Condition1: Proximity to main road or railroad
15. Condition2: Proximity to main road or railroad (if a second is present)
16. BldgType: Type of dwelling
17. HouseStyle: Style of dwelling
18. OverallQual: Overall material and finish quality
19. OverallCond: Overall condition rating
20. YearBuilt: Original construction date
21. YearRemodAdd: Remodel date
22. RoofStyle: Type of roof
23. RoofMatl: Roof material
24. Exterior1st: Exterior covering on house
25. Exterior2nd: Exterior covering on house (if more than one material)
26. MasVnrType: Masonry veneer type
27. MasVnrArea: Masonry veneer area in square feet
28. ExterQual: Exterior material quality
29. ExterCond: Present condition of the material on the exterior
30. Foundation: Type of foundation
31. BsmtQual: Height of the basement
32. BsmtCond: General condition of the basement
33. BsmtExposure: Walkout or garden level basement walls
34. BsmtFinType1: Quality of basement finished area
35. BsmtFinSF1: Type 1 finished square feet
36. BsmtFinType2: Quality of second finished area (if present)
37. BsmtFinSF2: Type 2 finished square feet
38. BsmtUnfSF: Unfinished square feet of basement area
39. TotalBsmtSF: Total square feet of basement area
40. Heating: Type of heating
41. HeatingQC: Heating quality and condition
42. CentralAir: Central air conditioning
43. Electrical: Electrical system
44. 1stFlrSF: First Floor square feet
45. 2ndFlrSF: Second floor square feet
46. LowQualFinSF: Low quality finished square feet (all floors)
47. GrLivArea: Above grade (ground) living area square feet
48. BsmtFullBath: Basement full bathrooms
49. BsmtHalfBath: Basement half bathrooms
50. FullBath: Full bathrooms above grade
51. HalfBath: Half baths above grade
52. Bedroom: Number of bedrooms above basement level
53. Kitchen: Number of kitchens
54. KitchenQual: Kitchen quality
55. TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)
56. Functional: Home functionality rating
57. Fireplaces: Number of fireplaces
58. FireplaceQu: Fireplace quality
59. GarageType: Garage location
60. GarageYrBlt: Year garage was built
61. GarageFinish: Interior finish of the garage
62. GarageCars: Size of garage in car capacity
63. GarageArea: Size of garage in square feet
64. GarageQual: Garage quality
65. GarageCond: Garage condition
66. PavedDrive: Paved driveway
67. WoodDeckSF: Wood deck area in square feet
68. OpenPorchSF: Open porch area in square feet
69. EnclosedPorch: Enclosed porch area in square feet
70. 3SsnPorch: Three season porch area in square feet
71. ScreenPorch: Screen porch area in square feet
72. PoolArea: Pool area in square feet
73. PoolQC: Pool quality
74. Fence: Fence quality
75. MiscFeature: Miscellaneous feature not covered in other categories
76. MiscVal: $Value of miscellaneous feature
77. MoSold: Month Sold
78. YrSold: Year Sold
79. SaleType: Type of sale
80. SaleCondition: Condition of sale

Data Preparation
Missing values
Categorical variables
Numeric variables
Ranking variables
Feature engineering
Correlation
Selecting the best variable

Modeling
Combine data (train and test)
Clean and fill in missing values
Separate train and test dataset
Split the training dataset into train and test
Train model and test
Use Gradient Boosting and Random forest regressors
Mean absolute error or mean square error
Predict on actual Kaggle test dataset

In [4]:
df.shape

(2919, 81)

In [5]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2919 non-null   int64
 1   MSSubClass     2919 non-null   int64
 2   MSZoning       2915 non-null   object
 3   LotFrontage    2433 non-null   float64
 4   LotArea        2919 non-null   int64
 5   Street         2919 non-null   object
 6   Alley          198 non-null    object
 7   LotShape       2919 non-null   object
 8   LandContour    2919 non-null   object
 9   Utilities      2917 non-null   object
 10  LotConfig      2919 non-null   object
 11  LandSlope      2919 non-null   object
 12  Neighborhood   2919 non-null   object
 13  Condition1     2919 non-null   object
 14  Condition2     2919 non-null   object
 15  BldgType       2919 non-null   object
 16  HouseStyle     2919 non-null   object
 17  OverallQual    2919 non-null   int64
 18  OverallCond    2919 non-null   int64
 19  YearBuilt      2919 non-null   int64
 20  YearRemodAdd   2919 non-null   int64
 21  RoofStyle      2919 non-null   object
 22  RoofMatl       2919 non-null   object
 23  Exterior1st    2918 non-null   object
 24  Exterior2nd    2918 non-null   object
 25  MasVnrType     2895 non-null   object
 26  MasVnrArea     2896 non-null   float64
 27  ExterQual      2919 non-null   object
 28  ExterCond      2919 non-null   object
 29  Foundation     2919 non-null   object
 30  BsmtQual       2838 non-null   object
 31  BsmtCond       2837 non-null   object
 32  BsmtExposure   2837 non-null   object
 33  BsmtFinType1   2840 non-null   object
 34  BsmtFinSF1     2918 non-null   float64
 35  BsmtFinType2   2839 non-null   object
 36  BsmtFinSF2     2918 non-null   float64
 37  BsmtUnfSF      2918 non-null   float64
 38  TotalBsmtSF    2918 non-null   float64
 39  Heating        2919 non-null   object
 40  HeatingQC      2919 non-null   object
 41  CentralAir     2919 non-null   object
 42  Electrical     2918 non-null   object
 43  1stFlrSF       2919 non-null   int64
 44  2ndFlrSF       2919 non-null   int64
 45  LowQualFinSF   2919 non-null   int64
 46  GrLivArea      2919 non-null   int64
 47  BsmtFullBath   2917 non-null   float64
 48  BsmtHalfBath   2917 non-null   float64
 49  FullBath       2919 non-null   int64
 50  HalfBath       2919 non-null   int64
 51  BedroomAbvGr   2919 non-null   int64
 52  KitchenAbvGr   2919 non-null   int64
 53  KitchenQual    2918 non-null   object
 54  TotRmsAbvGrd   2919 non-null   int64
 55  Functional     2917 non-null   object
 56  Fireplaces     2919 non-null   int64
 57  FireplaceQu    1499 non-null   object
 58  GarageType     2762 non-null   object
 59  GarageYrBlt    2760 non-null   float64
 60  GarageFinish   2760 non-null   object
 61  GarageCars     2918 non-null   float64
 62  GarageArea     2918 non-null   float64
 63  GarageQual     2760 non-null   object
 64  GarageCond     2760 non-null   object
 65  PavedDrive     2919 non-null   object
 66  WoodDeckSF     2919 non-null   int64
 67  OpenPorchSF    2919 non-null   int64
 68  EnclosedPorch  2919 non-null   int64
 69  3SsnPorch      2919 non-null   int64
 70  ScreenPorch    2919 non-null   int64
 71  PoolArea       2919 non-null   int64
 72  PoolQC         10 non-null     object
 73  Fence          571 non-null    object
 74  MiscFeature    105 non-null    object
 75  MiscVal        2919 non-null   int64
 76  MoSold         2919 non-null   int64
 77  YrSold         2919 non-null   int64
 78  SaleType       2918 non-null   object
 79  SaleCondition  2919 non-null   object
 80  SalePrice      1460 non-null   float64
dtypes: float64(12), int64(26), object(43)
memory usage: 1.8+ MB

In [7]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,2919.000000,2919.000000,2433.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2896.000000,2918.000000,...,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,1460.000000
mean,1460.000000,57.137718,69.305795,10168.114080,6.089072,5.564577,1971.312778,1984.264474,102.201312,441.423235,...,93.709832,47.486811,23.098321,2.602261,16.062350,2.251799,50.825968,6.213087,2007.792737,180921.195890
std,842.787043,42.517628,23.344905,7886.996359,1.409947,1.113131,30.291442,20.894344,179.334253,455.610826,...,126.526589,67.575493,64.244246,25.188169,56.184365,35.663946,567.402211,2.714762,1.314964,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,730.500000,20.000000,59.000000,7478.000000,5.000000,5.000000,1953.500000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129975.000000
50%,1460.000000,50.000000,68.000000,9453.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,368.500000,...,0.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,2189.500000,70.000000,80.000000,11570.000000,7.000000,6.000000,2001.000000,2004.000000,164.000000,733.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,2919.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [8]:
df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       486
LotArea             0
                 ...
MoSold              0
YrSold              0
SaleType            1
SaleCondition       0
SalePrice        1459
Length: 81, dtype: int64

In [9]:
from statistics import mode

In [10]:
for column in df.columns:
    if column != 'SalePrice':
        if df[column].dtype == 'int' or df[column].dtype == 'float':
            column_mean = df[column].mean()
            df[column].fillna(column_mean, inplace=True)
        elif df[column].dtype == 'object':
            column_mode = mode(df[column].dropna())
            df[column].fillna(column_mode, inplace=True)
#eÄer kolonda sayÄ±lar varsa sayÄ±larÄ±n ortalamasÄ±nÄ± boÅluklara yerleÅtirdik, eÄer string deÄerler 
#varsa en Ã§ok tekrarlanan deÄeri boÅluklara yerleÅtirdik

In [11]:
for column in df.columns:
    if column != 'SalePrice': #saleprice kolonu hariÃ§ her kolona data encoding yapÄ±yorum
        value_counts = df[column].value_counts()
        num_categories = len(value_counts)
        
        # Ä°ki alt kategorisi varsa 0 ve 1 olarak kodlayalÄ±m
        if num_categories == 2:
            category_mapping = {category: index for index, category in enumerate(value_counts.index)}
            df[column] = df[column].map(category_mapping)
        # Ä°ki alt kategoriden fazlaysa 1'den baÅlayan sÄ±ralÄ± sayÄ±larla kodlayalÄ±m
        else:
            category_mapping = {category: index + 1 for index, category in enumerate(value_counts.index)}
            df[column] = df[column].map(category_mapping)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2919 non-null   int64
 1   MSSubClass     2919 non-null   int64
 2   MSZoning       2919 non-null   int64
 3   LotFrontage    2919 non-null   int64
 4   LotArea        2919 non-null   int64
 5   Street         2919 non-null   int64
 6   Alley          2919 non-null   int64
 7   LotShape       2919 non-null   int64
 8   LandContour    2919 non-null   int64
 9   Utilities      2919 non-null   int64
 10  LotConfig      2919 non-null   int64
 11  LandSlope      2919 non-null   int64
 12  Neighborhood   2919 non-null   int64
 13  Condition1     2919 non-null   int64
 14  Condition2     2919 non-null   int64
 15  BldgType       2919 non-null   int64
 16  HouseStyle     2919 non-null   int64
 17  OverallQual    2919 non-null   int64
 18  OverallCond    2919 non-null   int64
 19  YearBuilt      2919 non-null   int64
 20  YearRemodAdd   2919 non-null   int64
 21  RoofStyle      2919 non-null   int64
 22  RoofMatl       2919 non-null   int64
 23  Exterior1st    2919 non-null   int64
 24  Exterior2nd    2919 non-null   int64
 25  MasVnrType     2919 non-null   int64
 26  MasVnrArea     2919 non-null   int64
 27  ExterQual      2919 non-null   int64
 28  ExterCond      2919 non-null   int64
 29  Foundation     2919 non-null   int64
 30  BsmtQual       2919 non-null   int64
 31  BsmtCond       2919 non-null   int64
 32  BsmtExposure   2919 non-null   int64
 33  BsmtFinType1   2919 non-null   int64
 34  BsmtFinSF1     2919 non-null   int64
 35  BsmtFinType2   2919 non-null   int64
 36  BsmtFinSF2     2919 non-null   int64
 37  BsmtUnfSF      2919 non-null   int64
 38  TotalBsmtSF    2919 non-null   int64
 39  Heating        2919 non-null   int64
 40  HeatingQC      2919 non-null   int64
 41  CentralAir     2919 non-null   int64
 42  Electrical     2919 non-null   int64
 43  1stFlrSF       2919 non-null   int64
 44  2ndFlrSF       2919 non-null   int64
 45  LowQualFinSF   2919 non-null   int64
 46  GrLivArea      2919 non-null   int64
 47  BsmtFullBath   2919 non-null   int64
 48  BsmtHalfBath   2919 non-null   int64
 49  FullBath       2919 non-null   int64
 50  HalfBath       2919 non-null   int64
 51  BedroomAbvGr   2919 non-null   int64
 52  KitchenAbvGr   2919 non-null   int64
 53  KitchenQual    2919 non-null   int64
 54  TotRmsAbvGrd   2919 non-null   int64
 55  Functional     2919 non-null   int64
 56  Fireplaces     2919 non-null   int64
 57  FireplaceQu    2919 non-null   int64
 58  GarageType     2919 non-null   int64
 59  GarageYrBlt    2919 non-null   int64
 60  GarageFinish   2919 non-null   int64
 61  GarageCars     2919 non-null   int64
 62  GarageArea     2919 non-null   int64
 63  GarageQual     2919 non-null   int64
 64  GarageCond     2919 non-null   int64
 65  PavedDrive     2919 non-null   int64
 66  WoodDeckSF     2919 non-null   int64
 67  OpenPorchSF    2919 non-null   int64
 68  EnclosedPorch  2919 non-null   int64
 69  3SsnPorch      2919 non-null   int64
 70  ScreenPorch    2919 non-null   int64
 71  PoolArea       2919 non-null   int64
 72  PoolQC         2919 non-null   int64
 73  Fence          2919 non-null   int64
 74  MiscFeature    2919 non-null   int64
 75  MiscVal        2919 non-null   int64
 76  MoSold         2919 non-null   int64
 77  YrSold         2919 non-null   int64
 78  SaleType       2919 non-null   int64
 79  SaleCondition  2919 non-null   int64
 80  SalePrice      1460 non-null   float64
dtypes: float64(1), int64(80)
memory usage: 1.8 MB

In [13]:
df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage         0
LotArea             0
                 ...
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice        1459
Length: 81, dtype: int64

In [14]:
columns_with_missing_values = df.columns[df.isna().any()] #sadece boÅ deÄeri bulunan kolon isileri

print(columns_with_missing_values)

#yokmuÅ

Index(['SalePrice'], dtype='object')

In [15]:
'''yaygÄ±n outlier tespit yÃ¶ntemi, IQR (Interquartile Range - Ãeyrekler ArasÄ± Menzil) yÃ¶ntemidir. 
IQR, veri kÃ¼mesinin alt Ã§eyrek ve Ã¼st Ã§eyrek arasÄ±ndaki mesafeyi ifade eder ve veri noktalarÄ±nÄ±n 
merkezsel yÃ¼zde 50'sini iÃ§erir. Bir veri noktasÄ±, alt Ã§eyrekten IQR'Ä±n 1.5 katÄ± daha kÃ¼Ã§Ã¼k veya Ã¼st
Ã§eyrekten IQR'Ä±n 1.5 katÄ± daha bÃ¼yÃ¼kse, bu veri noktasÄ± bir outlier olarak kabul edilir.'''

def remove_outliers(df):
    Q1 = df.quantile(0.25)
    Q3 = df.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_rows = ((df < lower_bound) | (df > upper_bound)).any(axis=1)
    df_filtered = df[~outlier_rows]
    return df_filtered

# Outlier'larÄ± tespit edelim ve veri kÃ¼mesinden Ã§Ä±karalÄ±m
df_without_outliers = remove_outliers(df)

In [16]:


# 'SalePrice' kolonundaki boÅ hÃ¼creleri en alta alarak tÃ¼m DataFrame'i sÄ±ralayalÄ±m
df_sorted = df.sort_values(by='SalePrice', na_position='last')

print(df_sorted)

        Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
495   1477           5         5            2     1133       0      0
916   2856           1         5            5        4       0      0
968   2908           3         2            5       57       0      0
533   1515           1         1            5       23       0      0
30    1925           6         5            5       62       0      1
...    ...         ...       ...          ...      ...     ...    ...
1454   977           7         2            9      245       0      0
1455   978           7         2            9      820       0      0
1456   979           1         1           91      819       0      0
1457   980          11         1           19     1951       0      0
1458  2919           2         1           17      163       0      0

      LotShape  LandContour  Utilities  ...  PoolArea  PoolQC  Fence  \
495          1            1          0  ...         1       1      3
916          1            1          0  ...         1       1      1
968          1            1          0  ...         1       1      3
533          1            4          0  ...         1       1      1
30           1            1          0  ...         1       1      1
...        ...          ...        ...  ...       ...     ...    ...
1454         1            1          0  ...         1       1      1
1455         1            1          0  ...         1       1      1
1456         1            1          0  ...         1       1      1
1457         1            1          0  ...         1       1      1
1458         1            1          0  ...         1       1      1

      MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice
495             1        1       9       2         1              3    34900.0
916             1        1       7       4         1              3    35311.0
968             1        1       3       2         1              3    37900.0
533             1        1      11       1         1              1    39300.0
30              1        1       2       3         1              1    40000.0
...           ...      ...     ...     ...       ...            ...        ...
1454            1        1       1       4         1              1        NaN
1455            1        1       4       4         1              3        NaN
1456            1        1       8       4         1              3        NaN
1457            1        7       2       4         1              1        NaN
1458            1        1       9       4         1              1        NaN

[2919 rows x 81 columns]

In [17]:
df.shape
#IQR tekniÄine gÃ¶re outlier yokmuÅ

(2919, 81)

In [18]:
train=df[:1454]
test=df[1454:]

In [19]:
train.shape,test.shape

((1454, 81), (1465, 81))

In [20]:
x_train=train.drop("SalePrice", axis=1)
y_train=train["SalePrice"]

In [21]:
x_test=test.drop("SalePrice", axis=1)
y_test=test["SalePrice"]

In [22]:
x_test.shape,y_test.shape

((1465, 80), (1465,))

In [23]:
from xgboost import XGBRegressor
xgb=XGBRegressor()
XGBC= XGBRegressor()
model=XGBC.fit(x_train,y_train)
pred=model.predict(x_test)

In [24]:
y_pred_xgb = model.predict(x_test)

In [25]:
y_pred_xgb=pd.DataFrame()

In [26]:
y_pred_xgb.to_csv("phprediction_xgb.csv",index=False)

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(x_train, y_train)


y_pred_rf = rf_classifier.predict(x_test)

In [28]:
y_pred_rf = pd.DataFrame()

In [29]:
y_pred_xgb.to_csv("phprediction_rf.csv",index=False)